### PR TITLE
add i18n for Esperanto + two fixes

### PR DESCRIPTION
**Pull request by B0pol**
Hi,
I added Esperanto to the list of languages.

By the way, I fixed two things : 
+ bengali, [which code is bn ](https://en.wikipedia.org/wiki/Bengali_language), was added in Resources_bn, but the declaration of the class was Resources_bg
+ testCalculatePreciseDurationMillenia() in PrettyTimeTest was saying 20 hours was expected instead of 14 hours.

I hope it will be merged soon @lincolnthree and you release an update for the library.

### CODE REVIEW

**Comment by lincolnthree** [comment]
Looks very good, thank you! Apologies for the delay in reviewing.

**Comment by B0pol** [comment]
Thank you ☺️

**Comment by B0pol** [comment]
Do you have an idea of the date when you wild release a new update?

**Comment by lincolnthree** [comment]
It has already been released.
https://repo1.maven.org/maven2/org/ocpsoft/prettytime/prettytime/4.0.3.Final/


Lincoln Baxter, III
http://ocpsoft.org
"Simpler is better."

**Pull request merged**
