### PR TITLE
Added Urdu Language Strings

### PR DESCRIPTION
**Pull request by alitele**
Here I added the time strings in urdu language to facilitate users who have urdu language in there application.

### CODE REVIEW

**Comment by alitele** [comment]
Yes I would love to be a contributor. :) One thing i want to know is how will my gradle dependency update , I mean I cannot see Resources_ur.java there. Please suggest.Thanks

**Comment by lincolnthree** [comment]
@alitele Awesome! To update I'll have to put out a new release of PrettyTime. I'll try to do that today.

**Comment by lincolnthree** [comment]
In the mean time, you can simply add your resources file to the classpath of your project.

**Comment by lincolnthree** [comment]
Released 4.0.2.Final. Should be available tomorrow.

**Comment by alitele** [comment]
Great @lincolnthree please share version 4.0.2.Final.

**Comment by lincolnthree** [comment]
It's released!

http://repo1.maven.org/maven2/org/ocpsoft/prettytime/prettytime/4.0.2.Final/

Lincoln Baxter, III
http://ocpsoft.org
"Simpler is better."

**Pull request merged**
