### PR TITLE
Added Burmese Language

### PR DESCRIPTION
**Pull request by vincent-paing**
Added my country(Myanmar)'s language Burmese (Code : MM)

### CODE REVIEW

**Comment by lincolnthree** [comment]
Hi Vincent! Thank you so much for this translation! I'm very happy to include it.

Would you also like to be listed as a contributor on the website? 

Thank you SO much!

**Comment by lincolnthree** [comment]
Also thank you for including a test :) This is a beautiful PR.

**Comment by lincolnthree** [comment]
There you go! http://www.ocpsoft.org/prettytime/

Release will be coming this week.

Thank you again :D

**Comment by vincent-paing** [comment]
@lincolnthree Sure, I would love to be listed as a contributor on the website. Thanks you so much 😄

**Pull request merged**
