### PR TITLE
Resources_az.java

### PR DESCRIPTION
**Pull request by Nizami20052022**
Added Azerbaijani language.

### CODE REVIEW

**Comment by Nizami20052022** [comment]
Merge this file, no more problems.

**Comment by lincolnthree** [comment]
@Nizami20052022 Great! Thank you so much for re-submitting :) I will get this reviewed & merged asap!

**Comment by lincolnthree** [comment]
This look good, thank you!!!

**Comment by lincolnthree** [comment]
Released 5.0.5.Final which includes these changes. It should be in Maven Central overnight.

**Comment by Nizami20052022** [comment]
Should I do something?

**Comment by lincolnthree** [comment]
> Should I do something?

Your changes have been merged and released in version 5.0.5.Final, so... probably update your project dependencies, but otherwise no -- this PR is complete.

**Pull request merged**
