### PR TITLE
Added Translation in Punjabi Language

### PR DESCRIPTION
**Pull request by ShareASmile**
Added Translation in Punjabi language
by adding resources_pa.java

### CODE REVIEW

**Comment by ShareASmile** [comment]
@lincolinthree i have made pa (Punjabi) language addition in petty time , you can take a look when free..

..& also  corrections have been made to "hi" (Hindi) language in #243
as both languages have been my local languages, thank you.

**Comment by lincolnthree** [comment]
Thanks so much for this translation :) I will review it and get it merged in ASAP. Your contributions will help make this library better for everyone!

**Comment by lincolnthree** [comment]
Can you tell me what you mean by " i am missing pa translations in NewPipe"?

Thanks!

**Comment by ShareASmile** [comment]
> Can you tell me what you mean by " i am missing pa translations in NewPipe

I meant any time specific translations like "moments ago" "just now" "a week ago" in youtube videos could not be seen in my local pa language in below mentioned NewPipe app which uses this library
https://github.com/TeamNewPipe/NewPipe/

There it shows only in English. 

Merging this PR will help show time related information in Punjabi language in any app that uses this library.

**Comment by lincolnthree** [comment]
Ah ok! Thanks for clarifying :) I was confused. I'll go ahead and get this reviewed, merged & released!

**Comment by lincolnthree** [comment]
Released 5.0.5.Final which includes these changes. It should be in Maven Central overnight.

**Comment by ShareASmile** [comment]
Thanks for merging @lincolnthree

**Pull request merged**
