### PR TITLE
Fix class location

### LINKED ISSUE #245: Weird class
It seems that this class is in the wrong place? 
https://github.com/ocpsoft/prettytime/blob/master/%C9%99sas/src/%C9%99sas/java/org/ocpsoft/g%C3%B6z%C9%99l%20vaxt/i18n/Resources_az.java   

/cc @lincolnthree

### PR DESCRIPTION
**Pull request by gastaldi**
- Fixes #245

### CODE REVIEW

**Comment by ShareASmile** [comment]
@lincolnthree I think this should be merged asap, prettytime 5.0.5 tag can be deleted in the meantime and recreated after merging this patch  so that prettytime 5.0.5 final which goes live on maven does contain this necessary patch.

**Comment by lincolnthree** [comment]
Dang that's an interesting one. Not sure how that got through the build process at all...

Thanks @gastaldi - you rule as always.

**Comment by lincolnthree** [comment]
@ShareASmile I do not believe artifacts can be removed from Maven. I will release 5.0.6

**Comment by lincolnthree** [comment]
Actually I never released it. Ok yes, we can still fix this version.

**Comment by lincolnthree** [comment]
@gastaldi How did you find this issue if I never released the JARs to central? Lol.

**Comment by gastaldi** [comment]
@lincolnthree I was browsing the repo to check the impact in the core in an environment using the Jakarta APis :)

**Comment by gastaldi** [comment]
Somehow the parent is not in central: https://repo.maven.apache.org/maven2/org/ocpsoft/prettytime/prettytime-parent/5.0.5.Final/prettytime-parent-5.0.5.Final.pom gives 404

**Comment by lincolnthree** [comment]
Lovely. That's the weirdest thing ever. I'll do a new release...

**Pull request merged**
