### PR TITLE
adding hebrew localization

### PR DESCRIPTION
**Pull request by alexitelman**

### CODE REVIEW

**Comment by lincolnthree** [comment]
Hey! Thanks for your help! I appreciate it and I apologize for the long time it took to get to this patch. Would you like to be listed as contributors on the prettytime homepage?

Also, is this different from the Resources_he file that was submitted just two days before yours? I notice a few small differences, but I think that they are pretty similar?

https://github.com/ocpsoft/prettytime/blob/master/core/src/main/java/org/ocpsoft/prettytime/i18n/Resources_he.java

Thanks,
Lincoln

**Comment by alexitelman** [comment]
Yes, it's a bit different, I think my translation is better, and also the other one doesn't have the 'iw' version, which is the locale identifier for Hebrew on some devices

**Comment by alexitelman** [comment]
And yes, it'd be nice to be listed as a contributer :)

**Comment by lincolnthree** [comment]
Okay. I'll get yours merged in. Thank you! Will add you as well.

**Comment by alexitelman** [comment]
Hey, I saw that you didn't get mine merged in yet.. Is there a problem?
Also, will this be available in the maven repo any time soon?

**Comment by lincolnthree** [comment]
Hey Alex, sorry for the delay. There are merge conflicts since the other versions have been merged. After resolving those, I noticed that you don't have tests for your files (and reasonably, the tests for the others are now broken.)

Is there any chance I could have you rebase and update your PR to address the test failures?

I've done the merge and pushed it to a branch so you can easily update: https://github.com/ocpsoft/prettytime/tree/alexitelman-master

Thanks!

**Comment by lincolnthree** [comment]
Once this is done, I will be happy to make a new release for you :)

**Comment by alexitelman** [comment]
Done. Please make a release.

On Mon, Nov 30, 2015 at 6:36 PM, Lincoln Baxter, III <
notifications@github.com> wrote:

> Once this is done, I will be happy to make a new release for you :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ocpsoft/prettytime/pull/113#issuecomment-160681698>.
>



-- 
With regards,
      Alex Itelman
      054-8855550
P*   Think Green. Do you really need to print this document?*

**Comment by alexitelman** [comment]
Sorry, the push failed. I have no permission. Can you give me some?

On Tue, Dec 1, 2015 at 10:18 AM, Alex Itelman <alex.itelman@gmail.com>
wrote:

> Done. Please make a release.
>
> On Mon, Nov 30, 2015 at 6:36 PM, Lincoln Baxter, III <
> notifications@github.com> wrote:
>
>> Once this is done, I will be happy to make a new release for you :)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ocpsoft/prettytime/pull/113#issuecomment-160681698>.
>>
>
>
>
> --
> With regards,
>       Alex Itelman
>       054-8855550
> P*   Think Green. Do you really need to print this document?*
>



-- 
With regards,
      Alex Itelman
      054-8855550
P*   Think Green. Do you really need to print this document?*

**Comment by alexitelman** [comment]
Nevermind, I tried to push to the branch in your fork... I updated my pull
request now.
Please make a release..

On Tue, Dec 1, 2015 at 10:19 AM, Alex Itelman <alex.itelman@gmail.com>
wrote:

> Sorry, the push failed. I have no permission. Can you give me some?
>
> On Tue, Dec 1, 2015 at 10:18 AM, Alex Itelman <alex.itelman@gmail.com>
> wrote:
>
>> Done. Please make a release.
>>
>> On Mon, Nov 30, 2015 at 6:36 PM, Lincoln Baxter, III <
>> notifications@github.com> wrote:
>>
>>> Once this is done, I will be happy to make a new release for you :)
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/ocpsoft/prettytime/pull/113#issuecomment-160681698>.
>>>
>>
>>
>>
>> --
>> With regards,
>>       Alex Itelman
>>       054-8855550
>> P*   Think Green. Do you really need to print this document?*
>>
>
>
>
> --
> With regards,
>       Alex Itelman
>       054-8855550
> P*   Think Green. Do you really need to print this document?*
>



-- 
With regards,
      Alex Itelman
      054-8855550
P*   Think Green. Do you really need to print this document?*

**Comment by lincolnthree** [comment]
Hey, it appears that there are still some failing tests. Do they all pass for you? 

```Failed tests:   testCalculatePreciceDurationMillenia(org.ocpsoft.prettytime.PrettyTimeI18n_HE_Test): expected:<...ודשים 1 שבוע 6 ימים [13] שעות 5 דקות> but was:<...ודשים 1 שבוע 6 ימים [20] שעות 5 דקות>
  testCalculatePreciceDurationMillenia(org.ocpsoft.prettytime.PrettyTimeI18n_IW_Test): expected:<...ודשים 1 שבוע 6 ימים [13] שעות 5 דקות> but was:<...ודשים 1 שבוע 6 ימים [20] שעות 5 דקות>
  testCalculatePreciceDurationMillenia(org.ocpsoft.prettytime.PrettyTimeTest): expected:<...onths 1 week 6 days [13] hours 5 minutes ago> but was:<...onths 1 week 6 days [20] hours 5 minutes ago>
```

**Comment by alexitelman** [comment]
How about now? (Something is different on my env and on your server)

**Comment by lincolnthree** [comment]
Perfect! Thank you! All tests green! Working on the release now.

**Comment by alexitelman** [comment]
Qhen will the release be ready? I want to try it

On Wednesday, 2 December 2015, Lincoln Baxter, III <notifications@github.com>
wrote:

> Merged #113 <https://github.com/ocpsoft/prettytime/pull/113>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ocpsoft/prettytime/pull/113#event-480298832>.
>


-- 
With regards,
      Alex Itelman
      054-8855550
P*   Think Green. Do you really need to print this document?*

**Comment by lincolnthree** [comment]
I just did the release in Maven Nexus. It should be available in a few hours!

**Comment by alexitelman** [comment]
I can't see it.. did it go through? What version is it? The latest I see is
4.0.0

On Thu, Dec 3, 2015 at 3:03 PM, Lincoln Baxter, III <
notifications@github.com> wrote:

> I just did the release in Maven Nexus. It should be available in a few
> hours!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ocpsoft/prettytime/pull/113#issuecomment-161630936>.
>



-- 
With regards,
      Alex Itelman
      054-8855550
P*   Think Green. Do you really need to print this document?*

**Comment by alexitelman** [comment]
Ok I see it now - 4.0.1 thanks

On Sunday, 6 December 2015, Alex Itelman <alex.itelman@gmail.com> wrote:

> I can't see it.. did it go through? What version is it? The latest I see
> is 4.0.0
>
> On Thu, Dec 3, 2015 at 3:03 PM, Lincoln Baxter, III <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> I just did the release in Maven Nexus. It should be available in a few
>> hours!
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ocpsoft/prettytime/pull/113#issuecomment-161630936>.
>>
>
>
>
> --
> With regards,
>       Alex Itelman
>       054-8855550
> P*   Think Green. Do you really need to print this document?*
>


-- 
With regards,
      Alex Itelman
      054-8855550
P*   Think Green. Do you really need to print this document?*

**Comment by lincolnthree** [comment]
4.0.1.Final

I see it in maven central.

--
Lincoln Baxter, III
http://ocpsoft.org
"Simpler is Better"

**Comment by alexitelman** [comment]
Yeah. Thanks, I used it.

On Tuesday, 8 December 2015, Lincoln Baxter, III <notifications@github.com>
wrote:

> 4.0.1.Final
>
> I see it in maven central.
>
> --
> Lincoln Baxter, III
> http://ocpsoft.org
> "Simpler is Better"
> On Dec 6, 2015 4:46 AM, "Alex Itelman" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > I can't see it.. did it go through? What version is it? The latest I see
> is
> > 4.0.0
> >
> > On Thu, Dec 3, 2015 at 3:03 PM, Lincoln Baxter, III <
> > notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > I just did the release in Maven Nexus. It should be available in a few
> > > hours!
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/ocpsoft/prettytime/pull/113#issuecomment-161630936
> >.
> > >
> >
> >
> >
> > --
> > With regards,
> > Alex Itelman
> > 054-8855550
> > P* Think Green. Do you really need to print this document?*
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ocpsoft/prettytime/pull/113#issuecomment-162292151>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ocpsoft/prettytime/pull/113#issuecomment-162690916>.
>


-- 
With regards,
      Alex Itelman
      054-8855550
P*   Think Green. Do you really need to print this document?*

**Pull request merged**
