### PR TITLE
Added Albanian translation and tests

### PR DESCRIPTION
**Pull request by AnXh3L0**

### CODE REVIEW

**Comment by lincolnthree** [comment]
Looks great! Thank you so much. Unless you object, I will add you to our translation contributors list :)

**Comment by lincolnthree** [comment]
Just FYI. I did need to rename the `Resources_en` class to `Resources_sq`, but other than that this came in cleanly. Much appreciatd!

**Comment by lincolnthree** [comment]
Version 4.0.5.Final has been released and includes this translation.

**Comment by AnXh3L0** [comment]
Ah, sorry about that, I missed the class name. Thanks a lot for your help merging this :)

**Pull request merged**
