### PR TITLE
Removed dot from minute short form in Polish

### PR DESCRIPTION
**Pull request by KaotikS**
According to Polish translators the final dot in "Minute" abbreviation should be removed.
Filed ticket: https://github.com/ocpsoft/prettytime/issues/135

### CODE REVIEW

**Comment by KaotikS** [comment]
Any change to get this PR merged?

**Comment by lincolnthree** [comment]
Sorry! Been a bit behind on this project. The PR looks good. Merging. Will be in the next release in the next week~ish.

**Comment by KaotikS** [comment]
Great, thank you very much!

Best regards

2017-05-08 21:09 GMT-03:00 Lincoln Baxter, III <notifications@github.com>:

**Comment by KaotikS** [comment]
Any idea about release date?

**Pull request merged**
