### PR TITLE
Update date arabic translation that would be fit in all arabic tens, gender, and plural

### PR DESCRIPTION
**Pull request by droiddevgirl**
Reff issue : https://github.com/ocpsoft/prettytime/issues/125

### CODE REVIEW

**Comment by lincolnthree** [comment]
Thanks for this PR! I could only vaguely follow the issue since I'm not too familiar with Arabic, but I'm glad you were able to come up with a solution. Does this PR address all the issues you referred to in Issue #125 or is there more to fix?

**Comment by lincolnthree** [comment]
Also, I noticed that some of the tests were removed. Out of curiosity (just so I am aware), what was the reason for this? Thanks again so much!

**Comment by droiddevgirl** [comment]
hi @lincolnthree 
1. Yes, this PR only for issues #125 
2. Ah i'm sorry i remove it by accident :scream: , i'll revert and update it :bow: 
Thanks

**Comment by droiddevgirl** [comment]
@lincolnthree i've update and revert accidentally removed code, please review again :bow: 
Thanks :smile:

**Comment by lincolnthree** [comment]
Fantastic! This looks great. I'll merge, and release a new version in the next few days/week.

Thank you so much!

**Pull request merged**
