### PR TITLE
OSGIfy pretty-time

### PR DESCRIPTION
**Pull request by amergey**
A proposal related to "Add manifest entries in jar to make it a valid OSGi bundle" issue

### CODE REVIEW

**Comment by lincolnthree** [comment]
Thank you! I will test this out ASAP.

**Comment by lincolnthree** [comment]
One question (while I am unable to try this myself - on a trip). Does this change to "bundle" packaging still result in a .jar artifact in the Maven repository? Aka, can it still be brought in as a normal JAR dependency in a Maven build? Or must the <type>bundle</type> be specified in the POM?

**Comment by amergey** [comment]
the result is still a jar file, with an osgi manifest, so it can be used either in a standalone java app or osgi app

**Comment by lincolnthree** [comment]
Sorry this took so long. Merged! Will be in the 4.0.1.Final release.

**Pull request merged**
