### PR TITLE
Added resources_az.java.

### PR DESCRIPTION
**Pull request by Nizami20052022**
Added Azerbaijani language.

### CODE REVIEW

**Comment by lincolnthree** [comment]
Hi @Nizami20052022,

Thanks so much for this PR :) I will review it and get it merged in ASAP. Your contributions will help make this library better for everyone!

**Comment by Nizami20052022** [comment]
I am very happy that I did.

**Comment by Nizami20052022** [comment]
I have to make some corrections, I can't.

**Comment by lincolnthree** [comment]
No worries. Should I wait to merge this? You should still be able to make more commits, right?

**Comment by Nizami20052022** [comment]
Merge this pull request. I can make some adjustments later.

**Comment by Nizami20052022** [comment]
Because the file cannot be edited.

**Comment by lincolnthree** [comment]
@Nizami20052022 You can make commits in your patch-2 branch directly, and you can also force-push to that branch to overwrite your existing changes. Let me know if that helps?

**Pull request closed without merging**
